# Development override for hot-reload
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: development
    command: ["uvicorn", "app.web.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
      - ./logs:/app/logs
    environment:
      DEBUG: "true"

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
      target: development
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    environment:
      DEBUG: "true"

  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
      target: development
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    environment:
      DEBUG: "true"